pipeline {
  agent {
    label 'server1'
  }
  stages {
    stage('build') {
      steps { 
        echo "This is build stage"
      }
    }
    stage('test') {
      steps {
        echo " This is test stage"
      }
    }
    stage('deploy') {
      steps {
        echo " this is deploy stage"
      }
    }
  }
}
