pipeline {
  agent {
    label 'server1'
  }
  tools {
  maven 'myMaven'
    }
  stages {
    stage('build') {
      steps { 
        sh 'mvn clean install'
      }
      post {
      success {
          archiveArtifacts artifacts: '**/target/*.war'
              }
            }
    }    
  }
}
